matchTiles=minecraft:block/leaves/natural/spruce_leaves
tiles=6,6,6,6
method=vertical
faces=bottom
biomes=snowy_tundra snowy_mountains snowy_taiga snowy_taiga_hills frozen_peaks snowy_plains snowy_beach ice_spikes windswept_hills windswept_forest meadow grove frozen_river