matchTiles=minecraft:block/leaves/spruce_leaves_top
tiles=5,5,5,5
method=vertical
faces=top
biomes=snowy_tundra snowy_mountains snowy_taiga snowy_taiga_hills frozen_peaks snowy_plains ice_spikes windswept_hills windswept_forest meadow grove frozen_river