matchTiles=minecraft:block/leaves/spruce_leaves
tiles=6,6,7,7
method=vertical
faces=sides
biomes=snowy_tundra snowy_mountains snowy_taiga snowy_taiga_hills frozen_peaks snowy_plains ice_spikes windswept_hills windswept_forest meadow grove frozen_river