method=overlay_vertical
method=overlay
tiles=<skip> <skip> <skip> <skip> <skip> <skip> ./15 <skip> ./15 <skip> ./15 ./15 ./15 ./15 <skip> ./15 <skip>
faces=sides
matchBlocks=dirt
connect=block
connectBlocks=snow_block
layer=cutout