export type DragonPhase =
  | 'holding_pattern'
  | 'strafe_player'
  | 'landing_approach'
  | 'landed'
  | 'breath_attack'
  | 'charge_player'
  | 'dying';

export interface DragonState {
  phase: DragonPhase;
  health: number;
  maxHealth: number;
  ticksInPhase: number;
  crystalsAlive: number;
  engagedPlayer?: string;
}

export const MAX_HEALTH = 200;

export function pickNextPhase(s: DragonState): DragonPhase {
  if (s.health <= 0) return 'dying';
  if (s.phase === 'holding_pattern' && s.ticksInPhase > 100 && s.engagedPlayer !== undefined) {
    return s.ticksInPhase % 2 === 0 ? 'strafe_player' : 'landing_approach';
  }
  if (s.phase === 'landed' && s.ticksInPhase > 200) return 'breath_attack';
  if (s.phase === 'breath_attack' && s.ticksInPhase > 400) return 'landing_approach';
  if (s.phase === 'landing_approach' && s.ticksInPhase > 80) return 'landed';
  if (s.phase === 'strafe_player' && s.ticksInPhase > 120) return 'holding_pattern';
  return s.phase;
}

// Wiki (minecraft.wiki/w/Ender_Dragon): "The ender dragon's health is
// regenerated by 1 HP every other game tick (10 HP per second) when
// within range of an active end crystal." That's 0.5 HP/tick from
// the nearest active crystal — NOT a per-crystal multiplier.
//
// Old `crystalsAlive * 0.01` was ~50× under the wiki rate (4 crystals
// gave 0.04 HP/tick vs wiki 0.5 HP/tick) and incorrectly scaled with
// crystal count instead of being a fixed-rate single-source heal.
export function healthRegenPerTick(s: DragonState): number {
  if (s.crystalsAlive <= 0) return 0;
  if (s.health >= s.maxHealth) return 0;
  return 0.5;
}
