// Nether dimension Y-bounds + ceiling behavior. The nether extends from
// y=0 to y=127 with a solid bedrock ceiling at y=127 (and y=0 floor).
// Entities cannot spawn above y=127 in the nether; beds placed under the
// ceiling still explode on use.

export const NETHER_FLOOR_Y = 0;
export const NETHER_CEILING_Y = 127;

export interface NetherBoundsQuery {
  y: number;
}

export function isAboveNetherCeiling(q: NetherBoundsQuery): boolean {
  return q.y >= NETHER_CEILING_Y;
}

export function isInNetherPlayableRange(q: NetherBoundsQuery): boolean {
  return q.y > NETHER_FLOOR_Y && q.y < NETHER_CEILING_Y;
}

// Mob spawn cap check: no hostile mobs above the ceiling.
export function canMobSpawnAt(y: number): boolean {
  return y >= NETHER_FLOOR_Y + 2 && y < NETHER_CEILING_Y - 1;
}

// Entering the nether from the overworld: Y is scaled 1:8 horizontally
// but Y is preserved unless it exceeds the ceiling (clamped to ceiling-3).
export function clampEntryY(requestedY: number): number {
  if (requestedY >= NETHER_CEILING_Y) return NETHER_CEILING_Y - 3;
  if (requestedY <= NETHER_FLOOR_Y) return NETHER_FLOOR_Y + 3;
  return requestedY;
}

// Bedrock positions generated by the chunk generator.
export interface BedrockLayer {
  y: number;
  probability: number;
}

export const BEDROCK_BOTTOM_LAYERS: readonly BedrockLayer[] = [
  { y: 0, probability: 1 },
  { y: 1, probability: 0.75 },
  { y: 2, probability: 0.5 },
  { y: 3, probability: 0.25 },
];

export const BEDROCK_CEILING_LAYERS: readonly BedrockLayer[] = [
  { y: 127, probability: 1 },
  { y: 126, probability: 0.75 },
  { y: 125, probability: 0.5 },
  { y: 124, probability: 0.25 },
];

export function shouldPlaceBedrock(
  y: number,
  layers: readonly BedrockLayer[],
  roll: number,
): boolean {
  const layer = layers.find((l) => l.y === y);
  if (!layer) return false;
  return roll < layer.probability;
}
